### ISSUE TITLE
Fixing of Skill Section of the Website

### ISSUE THREAD

**Issue by Deepjyoti-Sarmah** [AnjaliChoudharyAUS/CSS_HTML_Website#1]
Hi, @AnjaliChoudharyAUS I saw your personal Website , I liked it. But your Website has a padding issue with the skill section .
Would you like it if I try to fix this issue.

**Comment by AnjaliChoudharyAUS** [comment]
Yes sure Deepjyoti, feel free to fix.

**Comment by Deepjyoti-Sarmah** [comment]
Hello @AnjaliChoudharyAUS  I have redesigned your website , check it out and inform if any changes required , it is redone using NextJs and TailwindCSS . Hope you like it
